### ISSUE TITLE
delivery_address & delivery_whitelist set: E-Mails are sent to the original recipient address instead of delivery_address

### ISSUE THREAD

**Issue by danielsippel** [symfony/SwiftmailerBundle#103]
We are using swiftmailer-bundle v2.3.8

config.yml:
```yaml
swiftmailer:
    disable_delivery: false
    delivery_address: devs@developer.com
    delivery_whitelist:
        - "/@domain1.com$/"
        - "/@domain2.de$/"
```

E-Mails are sent to the original recipient address, although if the domain is not included in the delivery_whitelist config, e.g. email is delivered to foo@gmail.com instead of devs@developer.com

We are using the spool.
